backend:
  name: github
  repo: edpmuzik-coder/edpmuzik520streaming-
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "musicas"
    label: "Músicas"
    folder: "conteudo"
    create: true
    extension: "json"
    format: "json"
    fields:
      - { label: "Título da Música", name: "titulo", widget: "string" }
      - { label: "Nome do Artista", name: "artista", widget: "string" }
      - { label: "Escolher Arquivo de Áudio (.mp3)", name: "arquivo", widget: "file" }
